### ISSUE TITLE
Loss is nan when setting args.sparse=1 on Citeseer

### ISSUE THREAD

**Issue by ryy980622** [BorealisAI/SLAPS-GNN#3]
When I run the code on Citeseer and set args.sparse=1, I got a nan loss.
I debug the code and find that the values of edges calculated by function knn_fast() contain nan values.
How could I fix this bug? Thank you for your attention for this issue!

**Comment by baharefatemi** [comment]
Does the same problem happen if you comment out line 153 in utils.py? If that's the case, either the adj is not loaded properly or there are nodes with no connections. The fix for cases when there are nodes in the adj with no connections is to change line 150 to the following:
norm = norm_row + norm_col + 0.000000001 (a small number)

**Comment by ryy980622** [comment]
Thank you for your reply! The problem has been solved after fixing the code.
